import '@/app/globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const locale = 'ru'
  return (
    <html lang={locale}>
      <body className="flex flex-col gap-5 bg-[var(--color-secondary)]">
        <>{children}</>
      </body>
    </html>
  )
}
